#!/usr/bin/env php

<?php
ini_set('display_errors', '1');
error_reporting(E_ALL);

use App\App;

require __DIR__ . '/vendor/autoload.php';

App::boot();

if(isset($argv[1]) && $argv[1] == 'start') {
    $game = new \App\Game();
    $game->start();
}